### ISSUE TITLE
From not working with branch name

### ISSUE THREAD

**Issue by rubendinho** [Trampoline-CX/action-turbo-changed#70]
## 🐛 Bug Description / How to Reproduce

Hi I'm getting the below error trying to supply `from: main` to the action: 
`run failed: failed to resolve packages to run: commit main does not exist`

## ✅ Expected behavior

Per the documentation, I should be able to swap `HEAD^1` with `main` and it should just work. 

## 📦 Packages Concerned

-

## 🗒️ Details

This is the (reusable) workflow: 
```yml
on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string

jobs:
  check_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necessary so we have commit history to compare to

      - name: Did ${{ inputs.workspace }} change?
        id: changed
        uses: Trampoline-CX/action-turbo-changed@v1
        with:
          workspace: ${{ inputs.workspace }}
          from: main
```
